[package]
name = "syscall-trace"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
quote = "1.0.40"
syn = { version = "2.0.100", features = ["full", "extra-traits"] }

[lib]
proc-macro = true